[project]
name = "settings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deepmerge>=2.0",
    "ipykernel>=6.30.1",
    "pydantic>=2.11.7",
]
